#!/usr/bin/env bash
#Nginx is running, and listening on port 80 of all the servers active IPv4 IPs
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
