#!/usr/bin/env bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -f
sudo apt-get install apache2
sudo systemctl start apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo systemctl reload apache2
