#!/usr/bin/env bash
#setting up nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
REDIRECT_301="\\\trewrite ^/redirect_me https://www.nationalgeographic.com/animals/mammals/facts/domestic-dog permanent;"
sudo sed -i "41i $REDIRECT_301" /etc/nginx/sites-available/default
sudo service nginx restart
